"""Add book_image column to Interaction table

Revision ID: 34c5e3504de4
Revises: f25cfa89e9c0
Create Date: 2023-08-18 19:08:20.828333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c5e3504de4'
down_revision = 'f25cfa89e9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_column('book_image')

    # ### end Alembic commands ###
